"""change disease column from enum to varchar

Revision ID: 73b1bcabc33d
Revises: d1d4d11f784f
Create Date: 2026-07-05 10:31:15.870985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '73b1bcabc33d'
down_revision: Union[str, Sequence[str], None] = 'd1d4d11f784f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_predictions', 'disease',
               existing_type=mysql.ENUM('HEALTHY', 'COCCIDIOSIS', 'FOWL_POX', 'NEWCASTLE', 'UNKNOWN'),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_predictions', 'disease',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('HEALTHY', 'COCCIDIOSIS', 'FOWL_POX', 'NEWCASTLE', 'UNKNOWN'),
               existing_nullable=False)
    # ### end Alembic commands ###
